### PR TITLE
Operator bbox fix

### LINKED ISSUE #714: if an operator only has two stops, its convex hull is a LineString rather than a Polygon
This problem first came up with the NYC DOT, which operates the Staten Island Ferry (https://transit.land/feed-registry/operators/o-dr5r7-nycdot). It only has two stops, at the ends of the ferry route; its operator geometry (convex hull) has been computed as a LineString with just two points. This makes it complicated to parse client-side, if you're not guaranteed a polygon.

For the time being, we're manually edited the operator geometry to be a polygon: https://transit.land/dispatcher/changesets/2108

In the future, let's look into adding a buffer around stops so that an operator with only two stops gets a polygon.

Timeframe: Not urgent.

### PR DESCRIPTION
**Pull request by doublestranded**
closes #714

### CODE REVIEW

File: app/models/concerns/has_a_geographic_geometry.rb [hunk 1]
```diff
@@ -18,6 +18,9 @@ def self.convex_hull(entities, as: :geojson, projected: false)
       projected_geometries = entities.map { |e| e.geometry(as: :wkt, projected: true)}
       geometry_collection = RGeo::Geographic.simple_mercator_factory.projection_factory.collection(projected_geometries)
       convex_hull = geometry_collection.convex_hull
+      if (geometry_collection.size < 3)
```
Comment (doublestranded) [inline app/models/concerns/has_a_geographic_geometry.rb]: explain units
