### PR TITLE
Repeating stops distance calc fix

### LINKED ISSUE #418: Incorrect distances saved in SSP when stop is repeated

### PR DESCRIPTION
**Pull request by doublestranded**
Closes #418

### CODE REVIEW

File: app/services/gtfs_graph.rb [hunk 1]
```diff
@@ -98,11 +98,11 @@ def ssp_perform_async(trip_ids, agency_map, route_map, stop_map, rsp_map)
...
       rsp = RouteStopPattern.find_by_onestop_id!(onestop_id)
-      begin
+      #begin
         rsp_distances_map[onestop_id] = rsp.calculate_distances
-      rescue StandardError
-        log "Could not calculate distances #{onestop_id}"
-      end
+      #rescue StandardError
+      #  log "Could not calculate distances for Route Stop Pattern: #{onestop_id}"
+      #end
```
Comment (irees) [inline app/services/gtfs_graph.rb]: remove commented code
