### PR TITLE
Onestop id name truncation

### LINKED ISSUE #575: Onestop Id Invalid Geometry Hash
From the dispatcher, the import for Feed onestop id "f-9q8v-commuteorgshuttle" failed with:

Error Validation failed: Onestop invalid geometry hash

The culprit turned out to be insufficient truncation for route names, a problem that showed up in route stop pattern onestop ids.

### PR DESCRIPTION
**Pull request by doublestranded**
closes #575

### CODE REVIEW

File: app/services/onestop_id.rb [hunk 1]
```diff
@@ -87,6 +87,15 @@ class StopOnestopId < OnestopIdBase
...
     MODEL = Route
+
+    def to_s
+      geohash = @geohash[0...self.class::GEOHASH_MAX_LENGTH]
+      [
+        self.class::PREFIX,
+        geohash,
+        @name[0...RouteStopPatternOnestopId.max_name_length(geohash.length)],
+      ].join(COMPONENT_SEPARATOR)[0...self.class::MAX_LENGTH]
+    end
```
Comment (irees) [inline app/services/onestop_id.rb]: Write comment to mention we're reserving 14 characters (2x6 + 2 separators) for RSP components.
